worker_processes  auto;
worker_rlimit_nofile 500000;

events {
    use epoll;
    worker_connections 512;
}

http {
    access_log  off;
    error_log /dev/null emerg;

    upstream api {
        server api1:3000;
        server api2:3001;
        keepalive 500;
    }

    server {
        listen 9999;

        # Rotas específicas retornando status codes diretamente
        location /t/ {
            return 200 'Root Endpoint Response';
            add_header Content-Type text/plain;
        }

        location /t/users/create {
            if ($request_method = POST) {
                return 201 'User Created';
            }
            return 405 'Method Not Allowed';
            add_header Content-Type text/plain;
        }

        location /t/users/1 {
            return 200 'Find By Id Endpoint Response';
            add_header Content-Type text/plain;
        }
        
        location /t/users/search {
            return 200 'Search Endpoint Response';
            add_header Content-Type text/plain;
        }

        location /t/users/invalid-search {
            return 404 'Invalid Search Endpoint Response';
            add_header Content-Type text/plain;
        }

        # Proxy reverso para qualquer rota que não comece com /t/
        location / {
            proxy_buffering off;
            proxy_set_header Connection "";
            proxy_http_version 1.1;
            proxy_set_header Keep-Alive "";
            proxy_set_header Proxy-Connection "keep-alive";
            proxy_pass http://api;
        }
    }
}